### ISSUE TITLE
Add XML versions of models

### ISSUE THREAD

**Issue by arohr** [arjanverstoep/sach-modellierung#1]
The binary version makes it difficult to track differences between commits. Please add the XML versions to the repo and regenerate them before every commit.

**Comment by arjanverstoep** [comment]
Yes this is be a good idea. Initially, I decided against committing the XMLs as they are redundant, and cannot be used in the UaModeler. But the .ua-files are a disaster if you want to compare revisions. I will add the requested XMLs in the next commit.

**Comment by arohr** [comment]
Yes, they are redundant, but they are needed to configure an OPC UA server. But the main reason is the ability to compare revisions. 
Btw: With UaModeler you _can_ import the XML files!

**Comment by arohr** [comment]
I added them in my fork.
