### ISSUE TITLE
Reflection of the latest SA-CH specs

### ISSUE THREAD

**Issue by arohr** [arjanverstoep/sach-modellierung#3]
As far as I can see the current implementation does not yet reflect (all) the latest changes in the SA-CH specs. When can this expected to be done?

**Comment by arjanverstoep** [comment]
What changes are you referring to?

**Comment by arohr** [comment]
For example:
- NetworkDeviceType was removed
- Property DeviceType/GeoRef was removed
- Property DeviceType/Configuration/Technological was removed
- Variable ControllerType/Status/AccumState was added
- and so on...

**Comment by arohr** [comment]
Hold on, I already implemented some of the changes. I will try to merge.

**Comment by arjanverstoep** [comment]
I'm still holding on :-) And I fear I'll have very much fun merging your changes, as I have outstanding commits as well.

**Comment by arohr** [comment]
See my pull request: https://github.com/arjanverstoep/sach-modellierung/pull/4
